### ISSUE TITLE
Add a `shared` dir in tests for common functions between merkle lockup contracts

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#1001]
Ref https://github.com/sablier-labs/v2-core/issues/1000#issuecomment-2259313830

The idea is to do something similar to how core tests are structured: https://github.com/sablier-labs/v2-core/tree/staging/test/core/integration/concrete/lockup

**Comment by smol-ninja** [comment]
Duplicate of https://github.com/sablier-labs/v2-core/issues/1002.
