### ISSUE TITLE
Add more endpoints in `foundry.toml`

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#1003]
As mentioned in [slack](https://sablier.slack.com/archives/CSSNL10Q3/p1722349322054449), deploy to all EVM chains that Fjord are using.

**Comment by PaulRBerg** [comment]
<img width="700" src="https://github.com/user-attachments/assets/5c0f3d52-9cc9-445b-bb5f-df1f08d0bad2"/>
