### ISSUE TITLE
Add zero address check for sender

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#1008]
There is no check if the sender is a zero address.

Anybody can accidentally set sender as zero address when creating the streams. Now because other functions such as cancel, renounce etc. are sender only, the stream creator would not be able to use them.

Thus, the task is to add zero address check for sender.

### References
- https://github.com/sablier-labs/flow/issues/198
- https://github.com/sablier-labs/v2-core/discussions/38#discussioncomment-10210887

**Comment by PaulRBerg** [comment]
> it can lead to denial-of-service with those functionalities

That doesn't sound correct. Why would it be DoS?

**Comment by PaulRBerg** [comment]
Got it, thanks for explaining.
