### ISSUE TITLE
transferAdmin function has different function visibility from interface

### ISSUE THREAD

**Issue by SeungjinPark2** [sablier-labs/v2-core#1012]
In `IAdminable.sol` file, transferAdmin has `external` function visibility.
However, it can be seen that the function has `public` in implementation code in `Adminable.sol` file.
I might think this is not intended and `external` is more desirable.

**Comment by smol-ninja** [comment]
From the [solidity doc](https://docs.soliditylang.org/en/latest/contracts.html#interfaces):

> All declared functions must be external in the interface, even if they are public in the contract.
