### ISSUE TITLE
Update blast staging branch

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#1020]
Include periphery [blast contracts](https://github.com/sablier-labs/v2-periphery/tree/blast-l2/) in `staging-blast`

Created an issue to track this, as it will likely take more time than expected.

**Comment by smol-ninja** [comment]
Right. And what about zksync changes?

**Comment by andreivladbrg** [comment]
zksync is going to be easy, as we just need to include the periphery contracts in the [deploy script](https://github.com/sablier-labs/v2-core/blob/zkSync-l2/deploy/deploy.ts), as for blast, it has additional logic in `src`

**Comment by andreivladbrg** [comment]
similar to: https://github.com/sablier-labs/flow/issues/340#issuecomment-2511513817
maintaining the `chain/blast` branch is not worth it

**Comment by PaulRBerg** [comment]
@andreivladbrg let's close issues "as not planned" in cases like this
