### ISSUE TITLE
Standard naming for custom chain branches

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1023]
As we perform deployments to more and more EVM chains, it's becoming clear to me that we will need to maintain parallel branches, e.g. for zkSync (due to zkEVM) and IoTeX (due to them not supporting Solidity v0.8.26).

We should name the branches in a standardized way so that we can see the chains at a glance.

- [x] Rename `blast-l2` to `chain/blast`
- [x] Rename `zkSync-l2` to `chain/zkSync`

**Comment by smol-ninja** [comment]
How about just call it `chain/blast` instead of `chain/blast-l2`? Officially its just called Blast network.

**Comment by smol-ninja** [comment]
Resolved in:
1. https://github.com/sablier-labs/v2-core/tree/chain/zkSync
1. https://github.com/sablier-labs/v2-core/tree/chain/blast
1. https://github.com/sablier-labs/v2-periphery/tree/chain/blast
1. https://github.com/sablier-labs/v2-periphery/tree/chain/zkSync
1. https://github.com/sablier-labs/v2-deployments/tree/chain/blast
1. https://github.com/sablier-labs/docs/commit/bcd0e43a138a55d22b7e377d7ff974d2c1b4af61
