### ISSUE TITLE
Add broker parameter to the withdraw function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1033]
## Rationale

Make it possible to charge broker fees at withdrawal time. See https://github.com/sablier-labs/company-discussions/discussions/72.

A nice benefit of this feature is that it also makes it easier to offer automated withdrawals. The relayer can insert its own broker address and a non-zero fee when performing the automated withdrawal.

## Spec

- [ ] Add `broker` parameter in all `withdraw` functions
- [ ] Charge a fee from the withdrawn amount

**Comment by PaulRBerg** [comment]
On second thoughts, we cannot implement this because it would create MEV. The withdraw function is public.

Only [protocol fees](https://github.com/sablier-labs/v2-core/issues/1034) make sense for the withdraw function.

**Comment by smol-ninja** [comment]
Good catch about MEV.

**Comment by andreivladbrg** [comment]
> On second thoughts, we cannot implement this because it would create MEV. The withdraw function is public.

lol, how did we not think of this? It was so obvious, haha :))

basically, anyone could set the broker address to themselves to collect 10% of the tokens.

**Comment by PaulRBerg** [comment]
haha, thanks!

> how did we not think of this?

Fallibilism!
