### ISSUE TITLE
Get rid of "Events" helper in tests

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1045]
Starting [Solidity v0.8.21](https://github.com/ethereum/solidity/releases/tag/v0.8.21), events can be emitted from interface files.

So we can get rid of the `Events.t.sol` file and duplicated events there and instead import the interface files from `src`.

**Comment by andreivladbrg** [comment]
will address it in the test refactor PR https://github.com/sablier-labs/v2-core/tree/test/common-modifiers
