### ISSUE TITLE
Remove Merkle Lockup contracts from this repo

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#1072]
<sup>Originally discussed in https://github.com/sablier-labs/v2-core/discussions/1068</sup>

Remove merkle lockup contracts from this repo.

**Comment by andreivladbrg** [comment]
Should we make this change, after we finish all 1.3.0 features and changes?

**Comment by smol-ninja** [comment]
Sounds good.

**Comment by smol-ninja** [comment]
I am working on this.

**Comment by andreivladbrg** [comment]
wouldn't it be better to do it after https://github.com/sablier-labs/v2-core/pull/1084 ?
so that you don't copy testing logic related to batch?

**Comment by smol-ninja** [comment]
As a part of this PR, this is what I am thinking:

-  Remove merkle related contracts and tests
-  Add those to `v2-periphery`

While adding to `v2-periphery`, I will only copy whats relevant to merkle lockup contracts. While removing it in this PR, it does not seem to me that there will be many conflicts.

**Comment by smol-ninja** [comment]
@PaulRBerg sounds good.

@andreivladbrg removing core dir is a part of https://github.com/sablier-labs/v2-core/issues/1073

**Comment by smol-ninja** [comment]
I have renamed this issue and created relevant in the `airdrops` repo: https://github.com/sablier-labs/airdrops/issues

**Comment by PaulRBerg** [comment]
Closed by #1089
