### ISSUE TITLE
Combine all Lockups into a singleton contract

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#1074]
<sup>Originally discussed in https://github.com/sablier-labs/v2-core/discussions/1064</sup>

The task is to write a singleton contract that can represent all lockup streams and see if its viable.

**Comment by smol-ninja** [comment]
#### Question to @sablier-labs/solidity:
Should be have separate `MAX_COUNT` for segments and tranches (status quo); or should we use the same value for both? 

If you [look at their values](https://github.com/sablier-labs/v2-core/blob/main/script/Base.s.sol#L87-L131), they are very close to each other. Therefore, my recommendation is to use the same value for both. The common `MAX_COUNT` would be defined as the maximum value that does not let either of the two exceed Block gas limit.

**Comment by PaulRBerg** [comment]
Makes sense to use the same value.

**Comment by andreivladbrg** [comment]
i also agree that the same value for both is better

**Comment by smol-ninja** [comment]
### Test deployment of Lockup contract:
1. [Lockup deployment](https://sepolia.etherscan.io/address/0xac19f4181e58efb7094e0cb4e1bb18c79f6aadf4#code)
2. [VestingMath library](https://sepolia.etherscan.io/address/0x336903e9289dacd51cf397a2c0cd09f71b2485e8#code)
3. [Helpers library](https://sepolia.etherscan.io/address/0x420191da86aa6593df727a4f6c1ad7dc2993a20d#code)

### Remarks:
- Foundry automatically deploys and link libraries without have to explicitly specify them. [Warp output](https://app.warp.dev/block/pzn2IQGudaPV9TxE2bU9fe).
- Etherscan verification requires --libraries arguments ([foundry book](https://book.getfoundry.sh/reference/cli/forge/verify-contract#forge-verify-contract)). [Warp output](https://app.warp.dev/block/wN22uHcqLdHlQMlFl9u7aO).
- Once verified, Etherscan shows the library code on the contract page.

**Comment by smol-ninja** [comment]
Also, I don't know the answer but the `createWithDuration` on the singleton contract is cheaper than deployed Lockup Linear contract (keeping all parameters same).
1. [174,000 on singleton](https://sepolia.etherscan.io/tx/0xeb7e037ba3e82f44a49b691fffb8206256d35bbbfb201e13f4ecbeb084141664)
2. [205,120 on deployed LockupLinear](https://sepolia.etherscan.io/tx/0x9e379e6b4400c647ec3492e387c4960a187f9c04580fe39bed24a1b9a6fcd571)

Seems like calls to public libraries ain’t affecting the gas usage.
