### ISSUE TITLE
ETH fee in withdraw function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1076]
## Context

As discussed [here](https://github.com/sablier-labs/company-discussions/discussions/72#discussioncomment-11115807), we want to be able to monetize the Lockup streams by charging an ETH fee, since this is much easier than charging in USDC or the stream's token.

## Spec

- [x] Make all functions payable so that the UI can set a non-zero `msg.value`.
- [x] Allow anyone to call `withdrawFees` function, and always transfer the ETH fees to the contract admin.

Note: compared to the ETH fee in MerkleLockup, the fee in this proposal is *optional*. The goal is to keep the protocol free but monetize at the UI level — the Sablier UI would introduce a small ETH fee in the transactions signed by users.

**Comment by andreivladbrg** [comment]
Since we are talking about an ETH fee, why not charge it in both `create` and `withdraw` ? @PaulRBerg

**Comment by PaulRBerg** [comment]
Because [we've decided to charge only recipients](https://github.com/sablier-labs/company-discussions/discussions/71).

**Comment by smol-ninja** [comment]
#### Missing from specs:
- Allow admin to change fee
- Check `msg.fee >= setFee` in the `_withdraw` function

right @PaulRBerg?

**Comment by PaulRBerg** [comment]
No, @smol-ninja. Might you have missed the last paragraph from the OP?

**Comment by smol-ninja** [comment]
Yes I did.

**Comment by andreivladbrg** [comment]
I started working on this, and regarding step 2:

>> "If it is, add it to a storage variable that accumulates the ETH fee"

it is not required to have a storage variable for this, as there is a native `this.balance` opcode .

**Comment by smol-ninja** [comment]
Can someone make a direct transfer of ETH to the contract? If no, then looks good. If yes, then tracking would be useful for accounting purposes.

**Comment by PaulRBerg** [comment]
There are several different ways in which ETH can be airdropped in the contract, e.g. SELFDESTRUCT. See this [StackExchange Q&A](https://ethereum.stackexchange.com/q/166700/24693).

So yes, it'd be helpful for accounting purposes to introduce the storage variable. But I wonder if the gas overhead is worth it? We could treat the non-fee-related ETH deposits (which are super unlikely anyway) as just another kind of revenue.

**Comment by smol-ninja** [comment]
We didn't add any storage variable to track ETH fee in merkle lockup (didn't realise at that time). So a decision here would affect the logic there as well.

**Comment by andreivladbrg** [comment]
> So yes, it'd be helpful for accounting purposes to introduce the storage variable

Personally, I don’t find that helpful or worth it enough. 
Can’t we emit the fee taken in the event and sum the amounts through the subgraph to calculate the all-time revenue generated through the withdraw function? @razgraf

**Comment by razgraf** [comment]
+1 for the `fee` in an event

**Comment by PaulRBerg** [comment]
Due to an [issue with the `batch` function](https://github.com/sablier-labs/v2-core/issues/1090), we are unable to emit the fee in an event because calculating would require a huge refactor, which is simply not worth it. We can figure out how much we made in ETH through other means, e.g., Etherscan or subgraphs.

**Comment by PaulRBerg** [comment]
There must be a way to obtain these `msg.value` amounts somehow from a transaction hash. Perhaps from the RPC? (this may be needed to show users how much they paid in fees)

We will figure out a way to obtain the CSV exports, though we might not need them. We can take a snapshot of the ETH fee at the end of each month.

**Comment by PaulRBerg** [comment]
Understood. Unfortunately, the refactor cost is huge, and given the pressure to launch the fees ASAP, I suggest launching without including the fees in the event.
