### ISSUE TITLE
Use Etherscan V2 API keys

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1092]
https://github.com/sablier-labs/airdrops/pull/5#discussion_r1850948897

https://x.com/PaulRBerg/status/1849765766129737964

**Comment by andreivladbrg** [comment]
tried to see if it is possible, but i believe foundry has no support for this yet: https://github.com/foundry-rs/foundry/issues/9196

**Comment by smol-ninja** [comment]
Can we set a single variable such as `ETHERSCAN_API_KEY` in `.env.deployment.example` and then use the same key everywhere in `foundry.toml`? And when foundry supports it natively, we can switch to their approach.
