### ISSUE TITLE
Add a test to cover all branches in "tokenURI" function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1105]
I just noticed that this branch is not covered by any test:

https://github.com/sablier-labs/v2-core/blob/b2b33286d8411e0da49a2e7e3f632dafbd722951/src/LockupNFTDescriptor.sol#L80-L82

See [Codecov](https://app.codecov.io/gh/sablier-labs/v2-core/blob/staging/src%2FLockupNFTDescriptor.sol#L80).

**Comment by smol-ninja** [comment]
It is covered in [fork test](https://github.com/sablier-labs/v2-core/blob/staging/tests/fork/NFTDescriptor.t.sol). We can also do it through mock contracts but this fork test is pretty solid imo.

Going against what I suggested earlier, what if we add fork test to code coverage?

Thoughts?

**Comment by PaulRBerg** [comment]
Yeah maybe running the fork tests with a low number of runs would be good?

**Comment by smol-ninja** [comment]
The coverage increased as a result of including fork tests in the coverage path (https://github.com/sablier-labs/v2-core/commit/9ef51a35fe0abe97fd5e4e6e93074f5212e37cf8).

See [Codecov](https://app.codecov.io/github/sablier-labs/v2-core/commit/a05aad786477e9649bb6027ef4c529c5f909d598/blob/src/LockupNFTDescriptor.sol#L80).

<img width="1028" alt="Screenshot 2024-12-09 at 19 55 13" src="https://github.com/user-attachments/assets/02e7c3a7-ee5a-4ab6-bc68-e4490f7a05d1">
