### ISSUE TITLE
Fix `tokenURI` function and remove backwards compatility

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#1112]
Based on this [comment](https://github.com/sablier-labs/v2-core/pull/1108#discussion_r1878200880) we need to need to fix some strings in the `tokenURI` function, and based on [this discussion](https://github.com/sablier-labs/v2-core/discussions/1109) we will remove backwards compatibility.

**Comment by smol-ninja** [comment]
Yes @PaulRBerg. Thats what I have done in https://github.com/sablier-labs/v2-core/pull/1113. You can have a look at the previews in the PR description.
