### ISSUE TITLE
Manage permissions to transfer non-transferrable streams

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#1119]
<sup>Originally proposed in https://github.com/sablier-labs/company-discussions/discussions/59 by @maxdesalle</sup>

## Feature request
Allow senders to grant permission to an array of addresses, to which non-transferrable streams can be transferred to.

## Pseudo implementation

Following is just an approximation. _Actual implementation should be at the discretion of the developer implementing it_.

- [ ] Add a new storage variable
```solidity
mapping (address sender => address recipient => bool) public hasPermissionToReceive;
```
- [ ] Add two new sender only functions:

```solidity
function grantPermissionToReceive(address recipient) onlySender {
  hasPermissionToReceive[msg.sender][recipient] = true;
}

function revokePermissionToReceive(address recipient) onlySender {
  hasPermissionToReceive[msg.sender][recipient] = false;
}
```

or maybe one to perform both:

```solidity
function managePermissionToReceive(address recipient, bool permission) onlySender {
  hasPermissionToReceive[msg.sender][recipient] = permission;
}
```

- [ ] Modify `_update` to include the following logic:

```solidity
if (!_streams[streamId].isTransferable && hasPermissionToReceive[_streams[streamId].sender][recipient]) {
  return super._update(to, streamId, auth);
}
else {
  revert()
}
```

## Some notes

- This implementation grants permissions for all the streams created by the sender regardless of the underlying token.
- This would be one-way transfer, i.e., once transferred to the approved address, the user cannot get it back. So, should we allow both ways or is it fine? cc @maxdesalle and @PaulRBerg.

**Comment by smol-ninja** [comment]
@PaulRBerg that is my mistake. I have added a comment to [the discussion](https://github.com/sablier-labs/company-discussions/discussions/59#discussioncomment-11615682) to confirm the specs.

**Comment by PaulRBerg** [comment]
Closing as [we would like to get more user requests](https://github.com/sablier-labs/company-discussions/discussions/59#discussioncomment-11616741) before implementing this.
