### ISSUE TITLE
Write invariant test for `tokenURI`

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#519]
## Idea

It would be nice to add an invariant test for the `tokenURI` implemented in https://github.com/sablier-labs/v2-core/pull/440.

We could do it like this:

- Install [`svglint`](https://github.com/birjj/svglint) as a Node.js dev dependency
- Use [`vm.ffi`](https://book.getfoundry.sh/cheatcodes/ffi) to run `pnpm svglint` from within Solidity
- Define an invariant test like the one in the code snippet below
- Use Foundry's recently introduced [inline test configuration](https://book.getfoundry.sh/reference/config/inline-test-config) to override the default number of runs - as this would be a heavy-load test, which would read and write content to files.

I have tried to write it myself now, but I encountered [this bug in Foundry](https://github.com/foundry-rs/foundry/issues/5080), so I will just mark this as "backlog" for the time being.

## Code Snippet

```solidity
import { Base64 } from "solady/utils/Base64.sol";
import { LibString } from "solady/utils/LibString.sol";

/// @dev Extracts the SVG from a base-64 encoded token URI.
function extractSVG(string memory uri) internal returns (string memory) {
    string memory decodedURI = string(Base64.decode(uri));
    string memory sanitizedURI = decodedURI.replace({ search: "data:application/json;base64,", replacement: "" });
    string memory image = vm.parseJsonString(sanitizedURI, ".image");
    string memory sanitizedImage = image.replace({ search: "data:image/svg+xml;base64,", replacement: "" });
    string memory svg = string(Base64.decode(sanitizedImage));
    return svg;
}

/// forge-config: default.invariant.depth = 1
/// forge-config: default.invariant.runs = 1
function invariant_TokenURI() external useCurrentTimestamp {
    uint256 lastStreamId = lockupStore.lastStreamId();
    for (uint256 i = 0; i < lastStreamId; ++i) {
        uint256 streamId = lockupStore.streamIds(i);

        // Skip burned NFTs.
        if (lockup.getRecipient(streamId) == address(0)) {
            continue;
        }

        string memory uri = lockup.tokenURI(streamId);
        string memory svg = extractSVG(uri);
        string memory filePath = "test/nft.svg";
        vm.writeFile(filePath, svg);

        string[] memory inputs = new string[](3);
        inputs[0] = "pnpm";
        inputs[1] = "svglint";
        inputs[2] = filePath;

        // TODO: check result
        bytes memory response = vm.ffi(inputs);
        console2.logBytes(response);
    }
}
```

**Comment by PaulRBerg** [comment]
I think that this would be useful, but in the grand scheme of things, it doesn't matter that much. WDYT @sablier-labs/solidity?

**Comment by smol-ninja** [comment]
What was the invariant statement you had in your mind? I couldn't figure it out from the original description.

**Comment by PaulRBerg** [comment]
Basically test that different variations of the NFT (produced by the invariant campaign) always lead to a positive result when running `svglint`.

**Comment by smol-ninja** [comment]
Oh nice. That looks like a cool invariant, basically making sure that NFT SVG is always valid and follow the rules. However, the default rules of `svglint` only ensure that `svg` tags are used. So even the following would pass:

```html
<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000">
gibberish
</svg>
```

In order to make it work for our NFT requirements, we will have to write specific rules to guarantee that the NFT SVG is indeed valid for different URIs and not just a random SVG element.

> I think that this would be useful, but in the grand scheme of things, it doesn't matter that much

Agree and also it seems to be very complicated to implement.
