### ISSUE TITLE
Move "isWarm" and "isCold" to "SablierV2Lockup"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#610]
This is @IaroslavMazur's recommendation:

>  the `isCold()` function definition could be moved up the hierarchy tree to `SablierV2Lockup`.

Context:

https://github.com/sablier-labs/v2-core/blob/412ec3d3998a766507de96afdb26c797d2ae491d/src/SablierV2LockupLinear.sol#L172-L176

https://github.com/sablier-labs/v2-core/blob/412ec3d3998a766507de96afdb26c797d2ae491d/src/SablierV2LockupLinear.sol#L194-L198

**Comment by worksofallwin** [comment]
If this is a necessary fix, I would like to work on this.

**Comment by PaulRBerg** [comment]
No, not necessary for now. Will mark as "backlog".
