### ISSUE TITLE
Documentation nitpicks

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#611]
- [x] Add missing backtick [here](https://github.com/sablier-labs/v2-core/blob/3df030516c7e9044742313c7cf17f15fdc1e9b05/src/interfaces/ISablierV2LockupLinear.sol#L87)
- [x] Capitalize "lockup" in "lockup streaming" and "lockup streams", i.e., say "Lockup Streaming" and "Lockup Streams"

**Comment by worksofallwin** [comment]
can I work on this Issue?

`Capitalize "lockup" in "lockup streaming" and "lockup streams", i.e., say "Lockup Streaming" and "Lockup Streams"`
can you also explain where to update this?

**Comment by worksofallwin** [comment]
Sure!
