### ISSUE TITLE
Fix "expectEmit" in fork tests

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#618]
See this CI workflow run:

https://github.com/sablier-labs/v2-core/actions/runs/5521040705/jobs/10068674893

The error was:

> Expected an emit, but the call reverted instead. Ensure you're testing the happy path when using the `expectEmit` cheatcode

The issue is probably related to the recent breaking changes in Foundry.

**Comment by andreivladbrg** [comment]
It looks like we are not facing the issue anymore: 

https://github.com/sablier-labs/v2-core/actions/runs/5644037434/job/15287135686

Should we close this?

**Comment by PaulRBerg** [comment]
@andreivladbrg it's possible that the bug occurs only with certain inputs. Can you please investigate based on the inputs logged in the CI workflow run shared above?

**Comment by PaulRBerg** [comment]
Any updates on this @andreivladbrg?

Have you been able to reproduce the error?

**Comment by andreivladbrg** [comment]
It's been a while since I tested, but I couldn't reproduce it. I tried to decode the calldata, but I got the `"EvmError: Revert"` error. I still believe that the error has nothing to do with the inputs but is an issue with Foundry.

**Comment by PaulRBerg** [comment]
Very well! Thanks for confirming. I will tentatively close this issue.
