### ISSUE TITLE
Deploy Sablier V2 on the Arbitrum Goerli testnet

### ISSUE THREAD

**Issue by maxdesalle** [sablier-labs/v2-core#619]
One thing which would really help with integrations on Arbitrum, a potential one being with DeFrag, would be to have the protocol on the Arbitrum Goerli testnet.

**Comment by PaulRBerg** [comment]
Done!

You can share the following URL with the DeFrag team:

https://docs.sablier.com/contracts/v2/deployments#arbitrum-goerli

**Comment by maxdesalle** [comment]
Great work! Thank you.
