### ISSUE TITLE
Add utility for changing the protocol fee which uses the newly introduced "readCallers" cheat

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#628]
Refs:

- https://github.com/foundry-rs/forge-std/pull/400
- https://github.com/foundry-rs/foundry/pull/4884
- https://github.com/foundry-rs/foundry/issues/4875
- https://github.com/foundry-rs/foundry/pull/4884#issuecomment-1536569879

**Comment by SensationalShubham** [comment]
Can you suggest me something on how to do it? Any resources will be appreciated.

**Comment by PaulRBerg** [comment]
Sure, @SensationalShubham. The task is to basically turn the following code:

https://github.com/sablier-labs/v2-core/blob/4b0e06328462e6dfc867b2a342c8c0d811ed48a0/test/integration/concrete/lockup-linear/create-with-range/createWithRange.t.sol#L106-L109

Into a subroutine located in `Base.t.sol`, which:

1. Reads the current caller using the newly introduced `readCallers` cheat (see references above)
2. If the current caller is not the admin, change the prank to `users.admin`
3. Changes the protocol fee to a user-provided value
4. Changes the prank back to the original current caller

Note: you also need to upgrade to [PRBTest v0.6.1](https://github.com/PaulRBerg/prb-test/releases/tag/v0.6.1).

**Comment by andreivladbrg** [comment]
Should we close this since we are going to remove them? @PaulRBerg

**Comment by PaulRBerg** [comment]
Yep, closing.
