### ISSUE TITLE
Add "withdrawMultipleMax" function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#629]
Add a new function called `withdrawMultipleMax` that loops over a user-provided array of streams and calls [`withdrawMax`](https://github.com/sablier-labs/v2-core/blob/3df030516c7e9044742313c7cf17f15fdc1e9b05/src/abstracts/SablierV2Lockup.sol#L248) on each stream.

The goal is to enable recipients to exit all of their current streams. Particularly useful for integrations with aggregators like Zapper.

**Comment by PraneshASP** [comment]
Happy to take this on. Can you let me know how do you want me to proceed with the implementation? 

I'm assuming something like this:

```solidity
    function withdrawMultipleMax(uint256[] calldata streamIds, address[] calldata recipients) external override {
        uint256 _recipientsLength = recipients.length;
        if(streamIds.length != _recipientsLength) revert Errors.InvalidInput();
        uint256 iter;
        for(; iter < _recipientsLength; ) {
        uint256 _streamId = _streamIds[iter];
        withdraw({ streamId: _streamId to: recipients[iter], amount: _withdrawableAmountOf(_streamId) });
        unchecked { ++iter; }
        }
    }
```

**Comment by PaulRBerg** [comment]
Thanks for your interest @PraneshASP but this is in the backlog. We will not work on this task at any time in the near future. I will follow up when we do!

**Comment by PaulRBerg** [comment]
How valuable would this function be in the UI, @razgraf, @gavriliumircea?

AFAIK you are not currently using `withdrawMax` for single streams in the UI.

**Comment by gavriliumircea** [comment]
I don't think we are going to use this function either at least for now at the UI level. Right now we are using withdraw and withdrawMultiple for our actions, and everything works just fine.

**Comment by PaulRBerg** [comment]
Thanks @gavriliumircea. I have marked this issue as "backlog".

**Comment by PaulRBerg** [comment]
Closing due to other tasks having a higher priority.

We can revisit this feature for a future release of the protocol.
