### ISSUE TITLE
Add "transferrable" boolean flag in create stream parameter structs

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#630]
Some users may prefer the stream NFTs to not be transferrable.

To enable this functionality, we need to add `transferrable` boolean flag in the create stream parameter structs in [`DataTypes`](https://github.com/sablier-labs/v2-core/blob/3df030516c7e9044742313c7cf17f15fdc1e9b05/src/types/DataTypes.sol).

Related: [Gabriel Shapiro's tweet](https://twitter.com/lex_node/status/1537840850377449472).

**Comment by PaulRBerg** [comment]
The Parafi team requested this feature on a call yesterday.

**Comment by smol-ninja** [comment]
Which is the working branch for V2.x milestone?

**Comment by PaulRBerg** [comment]
@smol-ninja I created `2.1` now, but FYI it is the same as `main`.

https://github.com/sablier-labs/v2-core/tree/2.1

**Comment by PaulRBerg** [comment]
Closed via #668.
