### ISSUE TITLE
Check if OpenZeppelin can be removed from peer dependencies

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#635]
Requiring users to install OpenZeppelin v4.9.2 may clash with the user's installation of OpenZeppelin.

We technically only depend upon the `IERC20` interface, which should be the same across all OpenZeppelin V4/ V5 releases? 🧐

**Comment by andreivladbrg** [comment]
We don't only depend upon the `IERC20` interface, we also use OpenZeppelin for many other dependencies:

https://github.com/sablier-labs/v2-core/blob/b5d02b7f97bb81cde884b3585064f98d95989e53/src/abstracts/SablierV2Lockup.sol#L4-L5

https://github.com/sablier-labs/v2-core/blob/b5d02b7f97bb81cde884b3585064f98d95989e53/src/SablierV2LockupLinear.sol#L5-L6

https://github.com/sablier-labs/v2-core/blob/b5d02b7f97bb81cde884b3585064f98d95989e53/src/SablierV2NFTDescriptor.sol#L5-L8

**Comment by PaulRBerg** [comment]
Sorry, I was unclear in my original comment.

What I meant is that `IERC20` is the only OpenZeppelin interface that has to be provided by Sablier package users (when creating streams).

`ERC721` and the rest are irrelevant because package users never interact with them directly. For instance, they could use their own ERC-721 interface as long as there is a common denominator between that and our ERC-721. However, `IERC20` has to be exactly the same as OpenZeppelin's implementation.

For a better understanding of peer dependencies, read this [StackOverflow post](https://stackoverflow.com/a/34645112/3873510).

**Comment by PaulRBerg** [comment]
[Related tweet](https://twitter.com/PaulRBerg/status/1685352565678931969).

**Comment by PaulRBerg** [comment]
@waynehoover no. This issue is about Node.js dependencies. You are using submodules and remappings (which are a pain to work with, TBH, we are considering dropping them for good).

You may just have to run `foundryup` - they fixed this bug yesterday https://github.com/foundry-rs/foundry/issues/5447.

**Comment by PaulRBerg** [comment]
On a second read, your errors seems different from what I have seen before.

@waynehoover could you share a link to your code?

might be worth sharing this with the Foundry team so they can have a look (and open a GitHub issue in Foundry).

**Comment by PaulRBerg** [comment]
Francisco Giordano (OpenZeppelin) created a proposal in Solidity's forum to make interfaces structural:

https://forum.soliditylang.org/t/making-interfaces-structural/1790

**Comment by PaulRBerg** [comment]
@andreivladbrg can you take a look at this task, please?

**Comment by andreivladbrg** [comment]
> @andreivladbrg can you take a look at this task, please? 

The simplest and quickest solution that comes to mind is to change the `create` functions parameter from `IERC20` to `address`. Would you like to make the change? 

IMO it would improve the DX for integrators because they would not have to double import the interface:

```solidity
import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { IERC20 as SablierIERC20 } from "@sablier/v2-core/types/tokens/IERC20.sol";
```

**Comment by PaulRBerg** [comment]
That is a solution, yes, but this GitHub issues is specifically about investigating whether OpenZeppelin can be removed from the Node.js peer dependencies. Can you look into this, please?

**Comment by andreivladbrg** [comment]
Yes it can, why couldn't it be removed if we have them listed under [dependencies](https://github.com/sablier-labs/v2-core/blob/d1157b49ed4bceeff0c4e437c9f723e88c134d3a/package.json#L13-L16)?  

We could also add "^": `@openzeppelin/contracts": "^4.9.2",`

Also, you didn't answer my question from above, would you like to make the change?

BTW, I tried to replicate the scenario from your tweet but I couldn't, I even pushed a [commit](https://github.com/sablier-labs/allo-v2/commit/ca26ad9f04719b5fa9a4ca8440f4a96957296c90) in the allo-v2 fork to remove the `SablierIERC20` import. Now it seems to work which is odd.

**Comment by PaulRBerg** [comment]
@andreivladbrg let's discuss offline about Node.js peer dependencies.

> you didn't answer my question from above, would you like to make the change?

no.

as I've said; that change is not about this GitHub issue. Let's discuss offline.

**Comment by PaulRBerg** [comment]
As discussed on the phone, we are able to remove OpenZeppelin from peer dependencies because it doesn't matter what specific version of `IERC20` the user is consuming in their Node.js environment. All of OpenZeppelin's implementations are compatible with Sablier.
