### ISSUE TITLE
Add total amount in NFT descriptor cards

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#638]
## Task

Edit the sidelines to add the total amount next to the token currency.

That is, instead of "EXA", it should say "1.2k EXA".

## Context

Requested by Exactly Protocol:

<img width="300" alt="SCR-20230725-qlmr" src="https://github.com/sablier-labs/v2-core/assets/8782666/985c6b58-dda8-4a76-a27d-f4b09d670763">

**Comment by razgraf** [comment]
Hmm not sure I see why the amount would be more definite, both duration and amount are immutable.
Nevertheless, I still think we should include the total amount somewhere. The suggestion to add it on the edges had two reasons behind:
1. easier to add in code
2. I'm a bit wary of the UI bleeding out with two amount boxes side by side (we need to test some scenarios before swapping the duration box for another amount box)

Even if we go with the replacement, I'd still keep the duration in the NFT as well - so the choice becomes:
- amount in box, duration on edge
- amount on edge, duration in box

**Comment by PaulRBerg** [comment]
Yet another request for this feature, now coming from NFTFI.

> Another Q: Is it possible to add in the total stream amount to the image on OpenSea? It is missing some key details. We would love to include a vid/gif of the image in our tweet thread

**Comment by razgraf** [comment]
> What if we turn the side text where it says "EXA" into "1.2k EXA"?

I think this was the [initial](https://github.com/sablier-labs/v2-core/issues/638#issuecomment-1652121698) suggestion, right? 

By the way, in light of #671 we could also limit the "live" aspect of our NFT by [replacing](https://github.com/sablier-labs/v2-core/discussions/671#discussioncomment-6852030) some attributes with approximations or ones that evolve slower.

**Comment by PaulRBerg** [comment]
> I think this was the https://github.com/sablier-labs/v2-core/issues/638#issuecomment-1652121698 suggestion, right?

Yep, but I was not sure where exactly on the side lines you wanted to place the amount.

> we could also limit the "live" aspect of our NFT

I'll follow up in that discussion thread.

**Comment by PaulRBerg** [comment]
The more I think about this issue, the more I realize that the total amount is much more important than the streamed amount. This value is especially important for NFT lending, but also for simple payments - you care about how much this particular stream will eventually give you.

Are you guys cool with replacing the streamed amount with the total amount?

TBH nobody will notice the total amount if we put it on the sidelines.

**Comment by razgraf** [comment]
SGTM!

**Comment by PaulRBerg** [comment]
Great, @andreivladbrg you can work on this task in your next sprint.

**Comment by andreivladbrg** [comment]
> Great, @andreivladbrg you can work on this task in your next sprint.

Yes, which word should we use as a replacement? Instead of "Streamed", should we use "Amount"? I think "Total Amount" might be too long.

**Comment by PaulRBerg** [comment]
> which word should we use as a replacement?

"Total"
