### ISSUE TITLE
Emit ERC-4906 metadata updates in "transferFrom"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#670]
The goal is to refresh the NFT SVG on platforms like OpenSea whenever the NFT is transferred around.

**Comment by andreivladbrg** [comment]
How should the implementation look? 
1. emit an event only when `transfer` or `transferFrom` is called
2. emit an event on transfer and also when `burn` and `mint` functions are called

Both versions require the implementation of `_afterTokenTransfer` hook. However, for the second version we would need to do similar as we did for `_beforeTokenTransfer`:

https://github.com/sablier-labs/v2-core/blob/d1ca26db69a92f174fe372a9643431efd1dcec1e/src/abstracts/SablierV2Lockup.sol#L332

**Comment by PaulRBerg** [comment]
Option 2, but note that `transfer` does not exist in ERC-721. Only `transferFrom`. I think you meant to say `_transfer` (notice the underscore)?

Yes, the implementation would go in `_afterTokenTransfer`. No need to check for the zero address in this case.
