### ISSUE TITLE
Deploy to zkSync Era

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#687]
Requested by user on Crisp:

<img width="410" alt="Screenshot 2023-09-11 at 4 55 53 PM" src="https://github.com/sablier-labs/v2-core/assets/8782666/1b0054e8-2e33-4808-8473-2215886b3e81">

**Comment by razgraf** [comment]
I've created a feature request on canny for this. If more people vote on it we can consider adding support (deployment, subgraph, app).

https://sablier.canny.io/feature-requests/p/deploy-to-zksync-era
