### ISSUE TITLE
Emit the events before the hooks

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#717]
The events should be emitted before the hooks are called:

- https://github.com/sablier-labs/v2-core/blob/91887daff5872c7fa83fe3644b6f7582e9bffc0d/src/abstracts/SablierV2Lockup.sol#L213C31-L213C51
- https://github.com/sablier-labs/v2-core/blob/91887daff5872c7fa83fe3644b6f7582e9bffc0d/src/SablierV2LockupLinear.sol#L442

**Comment by andreivladbrg** [comment]
Why did you add this to `v2.2`. I think we can push this to main.

**Comment by PaulRBerg** [comment]
Yeah, I will remove it from the `2.2` project.
