### ISSUE TITLE
Run slither job periodically 

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#719]
In the latest PR, we added the slither job to our CI.

https://github.com/sablier-labs/v2-core/blob/3883dc3f3b2d33c7519292404e4942969a4dd2f2/.github/workflows/ci.yml#L289-L317

After it ran twice, I realized it might take significantly longer compared to other jobs:
https://github.com/sablier-labs/v2-core/actions/runs/6654049027

I believe it would be more efficient to move the slither job to a separate workflow, similar to the [deep job](https://github.com/sablier-labs/v2-core/blob/main/.github/workflows/ci-deep.yml) that runs weekly. We could schedule the slither job to run daily or weekly.

**Comment by PaulRBerg** [comment]
Agree

**Comment by PaulRBerg** [comment]
Closing as this has been implemented in #726.
