### ISSUE TITLE
Remove flash loans

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#733]
In light of:

1. Our recent [decision](https://github.com/sablier-labs/v2-periphery/issues/224) to remove the proxy targets from V2 Periphery
2. The fact that implementing them would be a [faff](https://github.com/sablier-labs/v2-interfaces/discussions/233)
3. The fact that they would act as a [deterrent](https://github.com/sablier-labs/v2-core/discussions/278) for vesting users
4. The reality that we have many other priorities

We should remove the flash loan logic from this repository; it increases the maintenance cost without adding any value.

**Comment by andreivladbrg** [comment]
> We should remove the flash loan logic from this repository;

does it mean that we should also change the comptroller contract?

https://github.com/sablier-labs/v2-core/blob/63204c9ab44e6f5efcb0c38249f229f7d4affe73/src/SablierV2Comptroller.sol#L39-L43

**Comment by PaulRBerg** [comment]
Yep.

Let's schedule this for V2.2
