### ISSUE TITLE
Add hooks for the sender side in `withdraw` function

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#742]
## Context

A user has asked us about how to automatically `cancel` a stream after it has been withdrawn a certain number of times by the recipient. 

Currently, this functionality is not possible at the contract level. Our implementation runs the hook only on the recipient's side:

https://github.com/sablier-labs/v2-core/blob/63204c9ab44e6f5efcb0c38249f229f7d4affe73/src/abstracts/SablierV2Lockup.sol#L283-L293

To address this we should  add a `ISablierV2LockupSender(sender).onStreamWithdrawn()` hook. This hook would be triggered when the caller is either the recipient or an approved operator.

**Comment by PaulRBerg** [comment]
Related: https://github.com/sablier-labs/v2-core/issues/736

**Comment by PaulRBerg** [comment]
Sers @razgraf and @gavriliumircea accede to this (we're on a call now).
