### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#747]
- [x] Forge Std 1.7.4
- [x] PRBMath v4.0.3 (I am due to release this)
- [x] Other dependencies listed in `package.json`

**Comment by PaulRBerg** [comment]
Forge Std change the visibility of `bound`, and this might cause some compilation warnings for users who use a more recent version of Forge Std.

See https://github.com/PaulRBerg/prb-math/pull/216 for more context.

**Comment by smol-ninja** [comment]
Closing as it has been completed via other PRs.
