### ISSUE TITLE
Change ASCII to say "Sablier V2.2"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#761]
It would be clearer if the ASCII differentiated the releases:

<img width="500" alt="SCR-20231221-lxhh" src="https://github.com/sablier-labs/v2-core/assets/8782666/a7c7cdf2-c588-4955-9037-ff18976dc135">

**Comment by andreivladbrg** [comment]
This is better than https://github.com/sablier-labs/v2-core/discussions/762

**Comment by andreivladbrg** [comment]
Can you paste here the site used for generating the ASCII?

**Comment by smol-ninja** [comment]
Did you use this? https://manytools.org/hacker-tools/ascii-banner/

**Comment by PaulRBerg** [comment]
>  Can you paste here the site used for generating the ASCII?

Sure: https://github.com/sablier-labs/v2-core/issues/288#issuecomment-1413453091

> Did you use this?

Nope

**Comment by PaulRBerg** [comment]
Putting this issue on hold whilst we agree on [how to version future contracts](https://github.com/sablier-labs/company-discussions/discussions/25).
