### ISSUE TITLE
Test the code identity between the Lockup contracts

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#771]
## Problem

Because [Solidity does not have anything equivalent to Rust traits](https://twitter.com/PaulRBerg/status/1531652974161838082), we are forced to duplicate any logic that touches upon different structs despite the logic being completely identical.

- [ ] [`_cancel`](https://github.com/sablier-labs/v2-core/blob/98d5281360c9e2d4c0cac7cc8d979e8dec571de9/src/SablierV2LockupLinear.sol#L385-L446)
- [ ] [`_renounce`](https://github.com/sablier-labs/v2-core/blob/98d5281360c9e2d4c0cac7cc8d979e8dec571de9/src/SablierV2LockupLinear.sol#L520-L528)
- [ ] [`_withdraw`](https://github.com/sablier-labs/v2-core/blob/98d5281360c9e2d4c0cac7cc8d979e8dec571de9/src/SablierV2LockupLinear.sol#L531-L556)

Technically speaking, there is a way out, but it's ugly and not worth it. We could implement a setter for every struct field (e.g., `setIsCancelable`, `setWasCanceled`, etc.), but:

1. Doing so would double the number of lines of code written for implementing the cancel and withdraw functionality
2. The gas cost would increase (there would be more internal calls, some of which may not be inlined)
3. There would still be a lot of duplicated code.

## Solution

Introduce a new class of tests, i.e. differential tests, that perform the following checks:

1. Read the `LockupLinear` and the `LockupDynamic` contracts (and potentially [`LockupTranched`](https://github.com/sablier-labs/private-discussions/discussions/19) in the future)
2. Compare the implementations of the `_cancel` and the `_withdraw` functions. They should be 100% identical, down to the English comments.
    - The [`awk` utility](https://www.geeksforgeeks.org/awk-command-unixlinux-examples/) might be helpful here

The tests would use Bash scripting and the [`ffi`](https://book.getfoundry.sh/cheatcodes/ffi?highlight=ffi#ffi) cheat code to read the file contents.

Alternatively, if implementing this in Forge is too complicated, we can write a CI check. There should be GitHub Actions for performing diffs between files.

## References

- https://book.getfoundry.sh/forge/differential-ffi-testing
- https://twitter.com/PaulRBerg/status/1531652974161838082
- https://github.com/sablier-labs/v2-core/pull/664#issuecomment-1689815366

**Comment by andreivladbrg** [comment]
Given how our test structure is designed (`shared` dir) is the code identity test really needed?  

We are running the same tests for these functions:`cancel`, `renounce` and `withdraw` in both contracts, so if there were to be difference between the implementations, the tests would fail for that contract (ofc assuming we have a 100% coverage for each function and we are testing what each line does).

I believe this test would be helpful only if we want to check if the comments are identical, thus we should lower the priority.

Regarding the test method, using forge seems to be an overkill. Adding a Bash script in the `shell` directory, which should be run during CI, would be more appropriate.

**Comment by PaulRBerg** [comment]
Yes, performing these code identity checks would still be helpful even if we run the same tests for these contracts.

1. Code identity is different from functional logic. The same test can pass for two different implementations. E.g., `1 + 3 = 2 +2`. So it's not just about the comments.
2. Fallibilism leads us to assume that we have made errors in our test suites (which are large and complicated). These code identity checks would be comparatively smaller, providing us additional confidence that everything works as expected.

> Regarding the test method, using forge seems to be an overkill. Adding a Bash script in the shell directory, which should be run during CI, would be more appropriate

Fair enough

**Comment by andreivladbrg** [comment]
@PaulRBerg since we implemented https://github.com/sablier-labs/v2-core/pull/813 should we close this issue?

**Comment by PaulRBerg** [comment]
Not sure. Isn't there duplicated code still?

If there is, we should keep this issue open (though revise the description in light of the new spec).

**Comment by andreivladbrg** [comment]
Just these, but I don't think they count

**Linear:** 

https://github.com/sablier-labs/v2-core/blob/aabd9356b3120aaecc3f4f95df14bd1957135085/src/SablierV2LockupLinear.sol#L123-L130

https://github.com/sablier-labs/v2-core/blob/aabd9356b3120aaecc3f4f95df14bd1957135085/src/SablierV2LockupLinear.sol#L238-L244

**Dynamic:**

https://github.com/sablier-labs/v2-core/blob/aabd9356b3120aaecc3f4f95df14bd1957135085/src/SablierV2LockupDynamic.sol#L135-L143

https://github.com/sablier-labs/v2-core/blob/aabd9356b3120aaecc3f4f95df14bd1957135085/src/SablierV2LockupDynamic.sol#L319-L325

Everything else is completely different

**Comment by PaulRBerg** [comment]
Yeah, they don't count, especially since we might end up removing protocol fees.
