### ISSUE TITLE
Standardize create functions

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#797]
As discussed in https://github.com/sablier-labs/company-discussions/discussions/20:

- [x] Rename `createWithDeltas` to `createWithDurations`
- [x] Rename `createWithMilestones` to `createWithTimestamps`
- [x] Rename `createWithRange` to `createWithTimestamps`

**Comment by andreivladbrg** [comment]
I think you've missed:
- `createWithMilestones` to `createWithTimestamps`

**Comment by PaulRBerg** [comment]
Corret

**Comment by andreivladbrg** [comment]
question, should we also rename `SegmentWithDelta` to `SegmentWithDuration`

and the [milestone argument](https://github.com/sablier-labs/v2-core/blob/7819a3b5122036596edff3326b97a8c03750bbb8/src/types/DataTypes.sol#L139) in the `Segment` should it be renamed to `timestampt`?

**Comment by PaulRBerg** [comment]
@andreivladbrg yes and yes.
