### ISSUE TITLE
Refactor all tests to use Bulloak

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#799]
See:

- https://github.com/alexfertel/bulloak
- https://prberg.com/presentations/solidity-summit-2023

**Comment by andreivladbrg** [comment]
I would mark this as priority 3

**Comment by PaulRBerg** [comment]
Can we please switch to Bulloak in the next release, or at least do it in `open-ended`?

Reviewing PRs that modify BTs without Bulloak is a **pain**

**Comment by smol-ninja** [comment]
Yeah lets do it in next release as well as use it in the first release of `open-ended`.

**Comment by PaulRBerg** [comment]
No objections. Just excitement!

**Comment by smol-ninja** [comment]
I have finished this. There are two PRs:
1. https://github.com/sablier-labs/v2-core/pull/1022 for core
2. https://github.com/sablier-labs/v2-core/pull/1025 for periphery
