### ISSUE TITLE
Upgrade GitHub Actions to get rid of Node.js v16 warning

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#812]
These warnings pop up in the CI summary, e.g. https://github.com/sablier-labs/v2-core/actions/runs/7755374062

<img width="400" alt="SCR-20240202-muyf" src="https://github.com/sablier-labs/v2-core/assets/8782666/f28a9b86-02be-439a-8c64-2ad382a79317">

**Comment by smol-ninja** [comment]
Related: https://github.com/sablier-labs/reusable-workflows/issues/2
