### ISSUE TITLE
Adjust versions in the NFT descriptor

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#820]
This is a child issue of https://github.com/sablier-labs/v2-core/issues/808.

The task is to adjust the description generated in the NFT descriptor to account for the package tethering, i.e., say LockupLinear v1.1.2 instead of Sablier V2:

https://github.com/sablier-labs/v2-core/blob/d5aea835dfe32b6cffa1c8cb40a7ba458f4ab5ee/src/SablierV2NFTDescriptor.sol#L261-L279

**Comment by PaulRBerg** [comment]
@andreivladbrg but @smol-ninja has suggested opening separate issues for each subtask.

I don't mind either way. You should resolve it between the two of you.

**Comment by smol-ninja** [comment]
As discussed privately, we decided to create multiple PRs for #808 instead of creating multiple sub-issues for it.
