### ISSUE TITLE
Use "vm.assume" in invariant tests

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#837]
They've recently added support for this feature in invariant tests - for a long time, `vm.assume` wasn't supported there, but it now is:

https://github.com/foundry-rs/foundry/issues/4190#event-12013303104

**Comment by andreivladbrg** [comment]
This is for `if(condition) return something;` in invariant handlers, right?

**Comment by PaulRBerg** [comment]
Yes, IIRC
