### ISSUE TITLE
Replace PRBTest with native Foundry assertions

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#842]
[Forge Std v1.8.0](https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0) has been released recently.

It comes with a wonderful new feature: native Foundry assertions! They got rid of DSTest.

This has motivated me to [deprecate PRBTest](https://github.com/PaulRBerg/prb-test/issues/45), hence why I also opened this issue here to replace PRBTest with the native assertions available in Foundry now.

Related:

- https://github.com/foundry-rs/forge-std/pull/503
- https://github.com/foundry-rs/forge-std/pull/514

**Comment by andreivladbrg** [comment]
> This has motivated me to https://github.com/PaulRBerg/prb-test/issues/45

so, it means one less dep? 

this issue requires to update the `forge-std` lib, thus more changes would be needed

**Comment by smol-ninja** [comment]
We would also have to replace `PRBTest` with native Foundry's `StdAssertions`  in [prb-math](https://github.com/PaulRBerg/prb-math/blob/v4.0.2/test/utils/Assertions.sol) as a requirement to this.

**Comment by PaulRBerg** [comment]
I'm OK with that.

**Comment by smol-ninja** [comment]
I have created a PR ([#222](https://github.com/PaulRBerg/prb-math/pull/222)) to update `forge-std` in `prb-math`.

**Comment by PaulRBerg** [comment]
Thanks for that, reviewed it now.
