### ISSUE TITLE
Rename Helpers functions

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#847]
These functions include "check" in theirs name, but we don't actually check anything; we only calculate the segments/tranches.

Therefore, should we rename it to `calculateSegmentTimestamps` and `calculateTrancheTimestamps` respectively?

https://github.com/sablier-labs/v2-core/blob/cbe1c0d61d74217d6ad01599318d5551f3381b2b/src/libraries/Helpers.sol#L143

https://github.com/sablier-labs/v2-core/blob/cbe1c0d61d74217d6ad01599318d5551f3381b2b/src/libraries/Helpers.sol#L176

**Comment by PaulRBerg** [comment]
Good catch

> should we rename it to `calculateSegmentTimestamps` and `calculateTrancheTimestamps` respectively?

Yes

**Comment by andreivladbrg** [comment]
> should we rename it to calculateSegmentTimestamps and calculateTrancheTimestamps respectively?
Yes

should we use plural instead? `calculateSegmentsTimestamps` and `calculateTranchesTimestamps`

**Comment by PaulRBerg** [comment]
Singular is OK in this situation
