### ISSUE TITLE
Deprecate `changePrank`

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#866]
The foundry cheatcode [`changePrank` has been deprecated](https://book.getfoundry.sh/reference/forge-std/change-prank) and will likely be removed in the future release.

Replacing it with `vm.startPrank` seems like a straightforward solution but it has introduced a new requirement that [the prank must have been applied atleast once before overriding](https://github.com/foundry-rs/foundry/blob/88e09f6f24a771b8b37def2d437660b13146bef6/crates/cheatcodes/src/evm/prank.rs#L107C1-L107C85). This has also been raised by @PaulRBerg in https://github.com/foundry-rs/foundry/issues/4942 but a shame that they decided to close it in favour of the suggestion to handle it using [readCallers](https://book.getfoundry.sh/cheatcodes/read-callers).

Since we decided to [update `forge-std`](https://github.com/sablier-labs/v2-core/issues/842), the tests now throw a deprecation warning. There are two solutions I can think of:
1. Carefully replace it with `vm.startPrank`.
2. Implement a `changePrank` function ourselves which calls `vm.stopPrank` followed by `vm.startPrank`.

Wdyt @PaulRBerg @andreivladbrg.
### Related
- https://github.com/foundry-rs/forge-std/pull/434

**Comment by andreivladbrg** [comment]
IMO it would be better if we implement a function ourselves that replicates the `changePrank` (i would name it differently)

**Comment by smol-ninja** [comment]
I agree with you Andrei. On the name how about `resetPrank`?

**Comment by smol-ninja** [comment]
Addressed in https://github.com/sablier-labs/v2-core/pull/865/commits/169947eebab9975fbc736af259475546610633de.

**Comment by smol-ninja** [comment]
Do you like the name @andreivladbrg or want to suggest something else?

**Comment by PaulRBerg** [comment]
I agree with @andreivladbrg, let's go with the path of least resistance and re-implement `changePrank` ourselves.

`resetPrank` works!
