### ISSUE TITLE
Robust script for estimating the max segment and the tranche counts

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#872]
## Context

While reviewing Shub's gas estimation script [here](https://github.com/sablier-labs/v2-core/discussions/823#discussioncomment-8945581), it dawned on me that we have been too lax about the values of `MAX_SEGMENT_COUNT` and `MAX_TRANCHE_COUNT`.

Basically, we have relied on heuristics and quick-and-dirty scripts to obtain them.

It's about time to develop a robust shell script for estimating the max segment and the tranche counts. My rationale is thus:

- We are deploying to 10+ chains, a number which will only increase over time
- Chains can change their total gas limit, which may require us to be agile and redeploy the contracts with new max counts
- There are nuances regarding the block gas limits on some chains such as [Avalanche](https://twitter.com/PaulRBerg/status/1773785345529704914)

## Mechanism of Action

The script would work something like this:

- Hard-code the (known) block gas limits for our deployment chains (until Forge Std implements my [feature request](https://github.com/foundry-rs/forge-std/issues/535))
- Gas golf `createWithDurations` (which is always more expensive than `createWithTimestamps`) until the consumed gas is right below the block gas limit per chain
- Allow the user to run the script for only one chain, or for all of them
- Subtract 10 from the previously obtained value (as an additional precaution)
- Do this for `LockupDynamic` and `LockupTranched` (separately)

A related suggestion is that we may want to turn the [`maxCount`](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/script/Base.s.sol#L48-L53) variable into a mapping in `BaseScript`.

**Comment by PaulRBerg** [comment]
Relevant information for how to read the block gas limit on OP Stack chains:

https://github.com/foundry-rs/forge-std/issues/535#issuecomment-2031648878

**Comment by PaulRBerg** [comment]
Are on track to complete this task by the time the private audit finishes in two weeks, @smol-ninja, @andreivladbrg?

**Comment by smol-ninja** [comment]
Yes. It will be done by then

**Comment by smol-ninja** [comment]
@PaulRBerg tagging you since its been added in https://github.com/sablier-labs/v2-core/pull/908.
