### ISSUE TITLE
Slight optimization in {Helpers-checkCreateWithTimestamps} for LockupLinear

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#878]
When the cliff time is zero, the following check is redundant because the cliff time can never be greater than the end time (thanks to the if checks at the beginning of the function):

https://github.com/sablier-labs/v2-core/blob/76e29fee33befaeb54a82473c28cf182e6f8855d/src/libraries/Helpers.sol#L105-L108

It just so happens that the [previous if](https://github.com/sablier-labs/v2-core/blob/76e29fee33befaeb54a82473c28cf182e6f8855d/src/libraries/Helpers.sol#L100-L103) checks the value of the cliff time. Thus, there's an opportunity to perform a gas optimization like this:

```solidity
// A cliff time of zero means there is no cliff, so we only perform the following checks if a cliff time is set.
if (range.cliff > 0) {
    // Check: the start time is strictly less than the cliff time.
    if (range.start >= range.cliff) {
        revert Errors.SablierV2LockupLinear_StartTimeNotLessThanCliffTime(range.start, range.cliff);
    }

    // Check: the cliff time is strictly less than the end time.
    if (range.cliff >= range.end) {
        revert Errors.SablierV2LockupLinear_CliffTimeNotLessThanEndTime(range.cliff, range.end);
    }
}
```

Cc @sablier-labs/solidity.

**Comment by smol-ninja** [comment]
Good observation.
