### ISSUE TITLE
FAIL. Reason: setup failed: Multiple matching artifacts found

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#886]
## Problem

It happens in CI when running the precompile tests:

https://github.com/sablier-labs/v2-core/actions/runs/8589580989/job/23536027804?pr=883

It also happens locally on recurring runs (first run is OK, subsequent runs aren't):

https://app.warp.dev/block/3kXDAuwyHk2pQmupBp5V2r

As @smol-ninja pointed out, this may be related to [Sphinx](https://www.sphinx.dev/).

## Solution

As per the advice received in the "Foundry Support" group on Telegram, one potential solution is to change the string paths passed to `vm.getCode`:

<img width="400" alt="SCR-20240408-kxzv" src="https://github.com/sablier-labs/v2-core/assets/8782666/d3806ca6-573e-401a-96ba-28cb2c89a1e9">

**Comment by smol-ninja** [comment]
Fixed in https://github.com/sablier-labs/v2-core/pull/883/commits/351ae0101421c994103ea5a8d66b1e7bd99a3779
