### ISSUE TITLE
Exclude clickjacking in security disclosure

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#920]
Here:

https://github.com/sablier-labs/v2-core/blob/main/SECURITY.md

**Comment by andreivladbrg** [comment]
@PaulRBerg your link points to the main page of the repo, is this intended? If yes, can you provide more details about the issue?

**Comment by PaulRBerg** [comment]
No, I have updated the OP with the correct URL, thanks @andreivladbrg
