### ISSUE TITLE
Add newlines between tag types

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#953]
### Discussed in https://github.com/sablier-labs/v2-core/discussions/906

Add [newlines between tag types](https://github.com/coinbase/solidity-style-guide?tab=readme-ov-file#3-newlines-between-tag-types) to improve readability.

```solidity
/// @notice Creates a new MerkleLockup campaign with a LockupLinear distribution.
/// @dev Emits a {CreateMerkleLL} event.
/// @param baseParams Struct encapsulating the {SablierV2MerkleLockup} parameters, which are documented in
/// {DataTypes}.
/// @param lockupLinear The address of the {SablierV2LockupLinear} contract.
/// @param streamDurations The durations for each stream.
/// @param aggregateAmount The total amount of ERC-20 assets to be distributed to all recipients.
/// @param recipientCount The total number of recipients who are eligible to claim.
/// @return merkleLL The address of the newly created MerkleLockup contract.
```

becomes 

```solidity
/// @notice Creates a new MerkleLockup campaign with a LockupLinear distribution.
///
/// @dev Emits a {CreateMerkleLL} event.
///
/// @param baseParams Struct encapsulating the {SablierV2MerkleLockup} parameters, which are documented in
/// {DataTypes}.
/// @param lockupLinear The address of the {SablierV2LockupLinear} contract.
/// @param streamDurations The durations for each stream.
/// @param aggregateAmount The total amount of ERC-20 assets to be distributed to all recipients.
/// @param recipientCount The total number of recipients who are eligible to claim.
///
/// @return merkleLL The address of the newly created MerkleLockup contract.
```

**Comment by smol-ninja** [comment]
As discussed with Andrei on slack (https://github.com/sablier-labs/v2-core/pull/1007/#issuecomment-2263005775).

**Comment by PaulRBerg** [comment]
Shouldn't we also remove the newlines in Flow?

**Comment by smol-ninja** [comment]
The use of newlines in `Flow` is already conditional, as shown in the screenshots below.

<img width="529" alt="Screenshot 2024-08-02 at 10 02 51" src="https://github.com/user-attachments/assets/0fe9e9b6-6a74-48e1-9391-0d5d4bc9c815">
<img width="585" alt="Screenshot 2024-08-02 at 10 02 46" src="https://github.com/user-attachments/assets/fa16e5b2-6637-46f3-8cd9-861d9f333af1">

But, do whatever you feel. I've started to have decision fatigue from this newline thing.
