### ISSUE TITLE
Fix chain ID for Blast network

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#967]
See below

https://github.com/sablier-labs/v2-core/blob/fd8eb98f4f88dfbfda35f6605662d84cb885f9c1/script/Base.s.sol#L101-L103

https://github.com/sablier-labs/v2-core/blob/fd8eb98f4f88dfbfda35f6605662d84cb885f9c1/benchmark/EstimateMaxCount.t.sol#L30

The correct chain ID is 81457, [source ↗](https://docs.blast.io/building/network-information).

Do the same in [blast-l2](https://github.com/sablier-labs/v2-core/tree/blast-l2) branch.

**Comment by PaulRBerg** [comment]
Does this mean that yesterday's deployment was incorrect and we have to redeploy?

**Comment by smol-ninja** [comment]
Not incorrect but with less number of segments and tranches. Chainlist had incorrect chain ID for Blast so as a result, I picked the wrong one without checking it in the Blast docs. Thats why it got deployed with the default values which is 500.

**Comment by smol-ninja** [comment]
Fixed https://github.com/sablier-labs/v2-core/commit/daeac7c23942ac465fd5da5d8291ecd433326e72.
