### ISSUE TITLE
Improve the deploy multi chain script

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#971]
With the latest release, I had to use the deploy multi chain script, and there are some things that we can do to improve the DX for this:
- don't exit the script execution if one chain's deployment fails, [ref](https://github.com/sablier-labs/v2-core/blob/daeac7c23942ac465fd5da5d8291ecd433326e72/shell/deploy-multi-chain.sh#L349-L352)
- generate only one deployment file (push with a header the deployment)
- don't delete the previous deployment (if already in file, copy it to a backup file)  
- print what CLI has been used
- mention in the deployment file if it is broadcasted or it is a simulation
- add a `cp` command to copy the broadcast file from the current dir to deployments dir (ofc first check if the dir exists at that path, if not skip it)
   - e.g. `cp broadcast/DeployDeterministicCore.s.sol/1/run-latest.json ../v2-deployments/core/v1.2.0/broadcasts/mainnet.json`

@smol-ninja tagging to ask for objections

**Comment by smol-ninja** [comment]
Good idea and no objection from my side.

**Comment by smol-ninja** [comment]
Should we close this @andreivladbrg ?

**Comment by andreivladbrg** [comment]
yes, we should, also created https://github.com/sablier-labs/v2-core/issues/1059
