### ISSUE TITLE
Remove redundat `Lockup` "namespace" in `Stream` struct

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#975]
In the current version of the common `Stream` struct, we declare the Amounts struct as:

https://github.com/sablier-labs/v2-core/blob/daeac7c23942ac465fd5da5d8291ecd433326e72/src/types/DataTypes.sol#L95

This is not needed as both of these structs are declared under `Lockup`.

**Comment by smol-ninja** [comment]
Good catch.
